#!/bin/bash

## wx: a METAR parser written in Bash
# (c) 2016 Allyson Bowles

## Usage:
# wx [[ temp [ f|F | c|C | k|K ]] | humidity | wind | altimeter | visibility | rvr | condition | phenomena | metar | remarks | refresh ]

## References:
# http://www.met.tamu.edu/class/metar/quick-metar.html
# http://www.dixwx.com/wxdecoding.htm

## Symbols: (for future use?)
# ❅ ☽ ☾ ☂ ☃ ☁ ⚡ ♨ ﹌ 〰 ⚐ ⚑ 〇    

## Dependencies:
# bc

## Constants
STATION=KMSN
# STATION=KMDW
# STATION=KHNB
DATA_URI="data/observations/metar/stations/$STATION.TXT"
#DATA_URL="http://weather.noaa.gov/pub/$DATA_URI"
DATA_URL="http://tgftp.nws.noaa.gov/$DATA_URI"
CACHE="$HOME/.cache/wx/metar"
TMP_CACHE="$HOME/.cache/wx/tmp"
TMP_CACHE_INTERVAL=5
TIMEOUT=10
SEPARATOR="#[fg=colour27]#[fg=colour33]"
PLATFORM=$(uname -a | awk '{ print $1 }')

metar=`cat $CACHE`

_check_md5sum() {
    case $PLATFORM in
        Linux)
            md5sum $1 | awk '{print $1}'
            ;;
        Darwin)
            md5 $1 | awk '{print $4}'
            ;;
    esac
}

refresh() {
    curl --connect-timeout $TIMEOUT --create-dirs -s $DATA_URL | tr "\n" " " > $TMP_CACHE
    if [[ "$?" -eq 0 && ! -f $CACHE ]]; then
        cp $TMP_CACHE $CACHE
    fi
    if [[ "$?" -eq 0 && $(_check_md5sum $TMP_CACHE) != $(_check_md5sum $CACHE) ]]; then
        cat $TMP_CACHE >> $(dirname $CACHE)/hist
        cp $TMP_CACHE $CACHE
    fi
}

metar() {
    echo $metar
}

remarks() {
    awk -F 'RMK' '{print $2}' <<< $metar
}

rvr() {
    awk '$0 ~ /(R[0-9]+/[0-9]+V?(M|P)[0-9]+FT)/' <<< $metar
}

phenomena() {
    phen=`echo $metar | awk -F 'RMK' '{print $1}' | grep -o '\(+\|-\)\b\(MI\|BL\|BC\|SH\|PR\|DR\|TS\|FZ\)\?\(DZ\|IC\|UP\|RA\|PL\|SN\|GR\|SG\|GS\)\?\(BR\|SA\|FU\|HZ\|VA\|PY\|DU\)\?\(SQ\|FC\|SS\|DS\|PO\)\?' | tr "\n" " "`

    case ${phen[0]} in
        +*) qual="heavy" ;;
        -*) qual="light" ;;
        VC*) ;; # vicinity
    esac

    case ${phen[0]} in
        *MI*) desc="shallow" ;;
        *BL*) desc="blowing" ;;
        *BC*) desc="patchy" ;;
        *SH*) desc="showers" ;;
        *PR*) desc="partial" ;;
        *DR*) desc="drifting" ;;
        *TS*) desc="thunderstorms" ;;
        *FZ*) desc="freezing" ;;
    esac

    case ${phen[0]} in
        *DZ*) precip="drizzle" ;;
        *IC*) precip="ice crystals" ;;
        *UP*) ;; # Unknown precipitation
        *RA*) precip="rain" ;;
        *PL*) precip="ice pellets" ;;
        *SN*) precip="snow" ;;
        *GR*) precip="hail" ;;
        *SG*) precip="snow grains" ;;
        *GS*) precip="small hail" ;;
    esac

    case ${phen[0]} in
        *BR*) obsc="mist" ;;
        *SA*) obsc="sand" ;;
        *FU*) obsc="smoke" ;;
        *HZ*) obsc="haze" ;;
        *VA*) obsc="volcanic ash" ;;
        *PY*) obsc="spray" ;;
        *DU*) obsc="dust" ;;
    esac

    case ${phen[0]} in
        *SQ*) other="squall" ;;
        *FC*) other="funnel cloud" ;;
        *SS*) other="sandstorm" ;;
        *FC*) other="tornado" ;;
        *DS*) other="dust storm" ;;
        *PO*) other="sand whirls" ;;
    esac

    if [[ -n "$qual" || -n "$desc" || -n "$precip" || -n "$obsc" || -n "$other" ]]
    then
        printf "%s " $qual $desc $precip $obsc $other $SEPARATOR
        exit 0
    else
        exit 1
    fi
}

condition() {
    cond=(`echo $metar | grep -o '\(\(CLR\|SKC\|FEW\|SCT\|BKN\|OVC\|VV\)\([0-9]\+\)\?\(\|TCU\|CB\)\?\)\+' | tr "\n" " "`)
    case ${cond[${#cond[@]} - 1]} in
        CLR*|SKC*) condition="clear" ;;
        FEW*) condition="partly cloudy" ;;
        SCT*) condition="cloudy" ;;
        BKN*) condition="mostly cloudy" ;;
        OVC*) condition="overcast" ;;
        **) condition="" ;;
    esac

    if [[ -n "$condition" ]]
    then
        printf "%s " $condition $SEPARATOR
        exit 0
    else
        exit 1
    fi
}

visibility() {
    grep -o '\([0-9]\+SM\)' <<< $metar
}

altimeter() {
    grep -o 'A[0-9]\{4\}' <<< $metar
}

wind() {
    wind_direction_speed=$(grep -o '[A-Z0-9]\+\(G[0-9]\+\)\?KT' <<< $metar)
    if test `echo $wind_direction_speed | grep -o 'G[0-9]\{2\}'`
    then
        wind_speed=$(grep -o '[0-9]\{2\}G[0-9]\{2\}KT' <<< $wind_direction_speed | awk -F 'G' '{print $1 * 1.151}' | bc)
        gusting=`echo $wind_direction_speed | grep -o 'G[0-9]\{2\}' | awk -F 'G' '{print $2 * 1.151}' | bc`
    else
        wind_speed=`echo $wind_direction_speed | grep -o '[0-9][0-9]KT' | awk -F 'KT' '{print $1 * 1.151}' | bc`
    fi
    wd=`echo $wind_direction_speed | cut -c 1-3`

    if [[ "$wd" == "VRB" ]]
    then
        wind_direction="variable"
    else
        wd=`echo $wd | bc`
        if ((1<=wd && wd<=11)) || ((347<=wd && wd<=360)); then wind_direction="N"
        elif ((12<=wd && wd<=33)); then wind_direction="NNE"
        elif ((34<=wd && wd<=56)); then wind_direction="NE"
        elif ((57<=wd && wd<=78)); then wind_direction="ENE"
        elif ((79<=wd && wd<=101)); then wind_direction="E"
        elif ((102<=wd && wd<=123)); then wind_direction="ESE"
        elif ((124<=wd && wd<=146)); then wind_direction="SE"
        elif ((147<=wd && wd<=168)); then wind_direction="SSE"
        elif ((167<=wd && wd<=191)); then wind_direction="S"
        elif ((192<=wd && wd<=213)); then wind_direction="SSW"
        elif ((214<=wd && wd<=236)); then wind_direction="SW"
        elif ((237<=wd && wd<=258)); then wind_direction="WSW"
        elif ((259<=wd && wd<=281)); then wind_direction="W"
        elif ((282<=wd && wd<=303)); then wind_direction="WNW"
        elif ((304<=wd && wd<=326)); then wind_direction="NW"
        elif ((327<=wd && wd<=346)); then wind_direction="NNW"
        else
            wind_direction=""
        fi
    fi

    if [[ "$wind_speed" == 0 || -z "$wind_speed" ]]
    then
        printf "calm"
    elif test `echo $wind_direction_speed | grep -o 'G[0-9]\{2\}'`
    then
        printf "%s %.0fmph gusting to %.0fmph" $wind_direction $wind_speed $gusting
    else
        printf "%s %.0fmph\n" $wind_direction $wind_speed
    fi
}

_temperature_dewpoint() {
    temperature_dewpoint=`grep -o '\s\([0-9]\{2\}\/[0-9]\{2\}\)\s' <<< $metar`
    read temp dp <<< $(awk -F '/' '{ printf "%d %d", $1, $2 }' <<< $temperature_dewpoint)
}

_degree_conversion() {
    case $2 in
        k|K) bc <<< "$1 + 270" | awk '{printf "%.0fK\n", $0}' ;;
        f|F) bc <<< "$1 * 9 / 5 + 32" | awk '{printf "%.0f°F\n", $0}' ;;
        **) printf "%d°C" $1 ;;
    esac
}

humidity() {
    _temperature_dewpoint
    humidity=$(bc -l <<< "100 * (e((17.625 * $dp)/(243.04 + $dp))/e((17.625 * $temp)/(243.04 + $temp)))")
    printf "%.0f%%" $humidity
}

temp() {
    _temperature_dewpoint
    _degree_conversion $temp $1
}

if test $(find $TMP_CACHE -mmin +$TMP_CACHE_INTERVAL); then
    refresh
fi

$1 $2
